require('dotenv').config();


const OPEN_AI_KEY = process.env.OPEN_AI_KEY;

async function getArticleContext(article) {
    const response = await fetch('https://api.openai.com/v1/chat/completions', {
        method: 'POST',
        headers: {
            'Content-Type': 'application/json',
            'Authorization': `Bearer ${OPEN_AI_KEY}`
        },
        body: JSON.stringify({
            model: "gpt-3.5-turbo",
            messages: [{
                role: "user",
                content: `Understand and summarize the main context of this article: ${article}`
            }]
        })
    });

    const data = await response.json();
    return data.choices[0].message.content;
}

async function explainExcerpt(articleContext, excerpt) {
    const response = await fetch('https://api.openai.com/v1/chat/completions', {
        method: 'POST',
        headers: {
            'Content-Type': 'application/json',
            'Authorization': `Bearer ${OPEN_AI_KEY}`
        },
        body: JSON.stringify({
            model: "gpt-3.5-turbo",
            messages: [
                {
                    role: "system",
                    content: `Using this article context: ${articleContext}`
                },
                {
                    role: "user",
                    content: `Explain this excerpt based on the article context: "${excerpt}"`
                }
            ]
        })
    });

    const data = await response.json();
    return data.choices[0].message.content;
}

// Usage example:
const article = `
Given the opportunity for a do-over thanks to a process error last month, the board of directors for Redwood Coast Energy Authority (RCEA) reversed course and decided to accept an allocation of nuclear energy into the mix of power it purchases on behalf of local ratepayers.

Unlike last time around, when the board expressed a lot of internal conflict over the decision, yesterday’s hearing at Eureka’s Wharfinger Building proved almost unanimous, with only Board Chair and Arcata representative Sarah Schaefer voting to reject the allocation. However, the board opted to accept the nuclear energy for only one year, while using the proceeds to invest in its renewable energy portfolio.

The vote required the RCEA board to make an exception to the agency’s Energy Risk Management Policy, which bans long-term nuclear energy procurement.

Diablo Canyon was supposed to be shut down by the end of 2025, but with California’s renewable energy development lagging behind schedule, the state legislature approved a $1.4 billion loan to PG&E to keep it operating through 2030. As part of that deal, all jurisdictional entities under the California Public Utilities Commission (CPUC) are paying a share of the costs, and they all have the option of receiving an allocation of the power generated by Diablo Canyon.

RCEA Community Strategies Manager Brytann Busick told the Outpost via email that the board deliberately chose to make this a short-term agreement.

“This opportunity to accept or reject the Diablo Canyon allocation will be brought before the Community Advisory Committee and Board of Directors each subsequent year until 2030,” Busisk said. “Community input would be sought again. Based on the acceptance of the allocation, there will be no impact on customer electricity bills.”

Reached by phone, RCEA Eureka representative Scott Bauer, who previously voted against taking the allocation, said the decision to keep Diablo Canyon operating was made by Gov. Gavin Newsom and the state government, so the only decision left to community choice aggregators like RCEA was whether to accept the “free” nuclear energy or stand on principle given the environmental implications, including the challenges of long-term nuclear waste storage.

This time around, the board chose to take the power that ratepayers are paying for.

“The end result was we’ll accept it but review [that decision] yearly, with hopes that maybe in a year or two we have so much renewables in our portfolio we can say we don’t want [nuclear] in our power mix,” Bauer said.

Specific allocation amounts have not yet been published, but according to an RCEA staff report, the local agency’s allocation would likely only meet about 2% of its 2025 power portfolio. 

Bauer said the savings won’t be enough to dramatically slash ratepayer bills.

“I did the math,” he said. “As a ratepayer the rebate would be 60 to 70 cents per month, which is pretty much insignificant.”

Instead, he said, RCEA plans to invest the savings in the development of more renewable energy sources.
`;

const excerpt = `RCEA Eureka `;

async function getExcerptExplanation(article, excerpt) {
    const context = await getArticleContext(article);
    const explanation = await explainExcerpt(context, excerpt);
    console.log(explanation);
    return explanation;
}

getExcerptExplanation(article, excerpt)
    .catch(error => console.error('Error:', error));